sudo: false

language: php

php:
    - 5.5
    - 5.6
    - 7.0

services:
    - mysql

before_script:
    - composer self-update || true
    - composer install
    - mysql -e 'create database icicle; use icicle; create table `test` (`id` int(11) unsigned not null auto_increment,`text` varchar(200) default null, primary key (`id`)) engine=InnoDB default charset=utf8;'

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - if ([ "$TRAVIS_PHP_VERSION" != "7.0" ]); then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
